"""
Probability distributions.
"""
from . import typing as t

def assert_proper(pi: t.ndarray) -> None: ...

def from_grid(grid: t.ndarray) -> t.ndarray: ...

def is_proper(pi: t.ndarray, mrd: t.FloatOrRat = t.def_mrd) -> bool: ...

def is_uniform(pi: t.ndarray, mrd: t.FloatOrRat = t.def_mrd) -> bool: ...

def normalize(pi: t.ndarray) -> t.ndarray: ...

def point(n_elem: int, x: int = 0, type: t.TypeLike = t.def_type) -> t.ndarray: ...

def randu(n_elem: int, type: t.TypeLike = t.def_type) -> t.ndarray: ...

@t.overload
def sample(pi: t.ndarray) -> int: ...
@t.overload
def sample(pi: t.ndarray, n_samples: int) -> t.ndarray: ...

def to_grid(pi: t.ndarray, width: int) -> t.ndarray: ...

def uniform(n_elem: int, type: t.TypeLike = t.def_type) -> t.ndarray: ...

