"""
Shannon entropy.
"""
from .. import typing as t

def add_capacity(C: t.ndarray, md: float = ..., mrd: float = ...) -> t.Tuple[float, t.ndarray]: ...

def add_leakage(pi: t.ndarray, C: t.ndarray) -> float: ...

def mult_leakage(pi: t.ndarray, C: t.ndarray) -> float: ...

def posterior(pi: t.ndarray, C: t.ndarray) -> float: ...

def prior(pi: t.ndarray) -> float: ...
