"""
Mechanism construction for geo-indistinguishability.
"""
from .. import typing as t

def planar_laplace_sample(epsilon: float) -> t.point: ...

def planar_laplace_grid(width: int, height: int, step: float, epsilon: float) -> t.ndarray: ...

@t.overload
def planar_geometric_sample(cell_size: float, epsilon: float) -> t.point: ...
@t.overload
def planar_geometric_sample(cell_size: float, epsilon: float, n_samples: int) -> t.List[t.point]: ...

def planar_geometric_grid(width: int, height: int, step: float, epsilon: float) -> t.ndarray: ...
